apiVersion: batch/v1
kind: Job
metadata:
  name: cfs-test
spec:
  template:
    spec:
      containers:
      - name: cfs-test
        command:
        - /bin/sh
        - -c
        - |
          cat /sys/fs/cgroup/cpu/cpu.cfs_period_us
          cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
          cat /sys/fs/cgroup/cpu/cpu.shares

          # /go/cfs -sleep 800ms -burn 200ms
          /go/cfs -sleep 0 -burn 200ms
          # /go/cfs -sleep 50ms -burn 50ms

          cat /sys/fs/cgroup/cpu/cpu.stat
        image: secret104278/cfs-test:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
          requests:
            cpu: 0
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      